### ISSUE TITLE
Not working with PPSSPP

### ISSUE THREAD

**Issue by jmoseman01** [ViGEm/ViGEm.NET#11]
**Describe the bug**
It's working with xinput tester for me but it's not allowing me to map buttons on ppsspp.

**To Reproduce**
Steps to reproduce the behavior (example):
1. open up ppsspp and try to map the axis 
2. run the following program
```C#
using System.Threading;
using Nefarius.ViGEm.Client;
using Nefarius.ViGEm.Client.Targets;
using Nefarius.ViGEm.Client.Targets.Xbox360;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            ViGEmClient client = new ViGEmClient();

            IXbox360Controller controller = client.CreateXbox360Controller();

            controller.Connect();
            Thread.Sleep(5000);

            while (true) {
                controller.SetAxisValue(Xbox360Axis.LeftThumbY, 3000);
                Thread.Sleep(10000);
            }

        }
    }
}
```

**Expected behavior**
I should be able to map the axis in ppsspp.

**Screenshots**
https://www.youtube.com/watch?v=EngEEFEUyXw

**System details (please complete the following information):**
OS: windows 10
Feeder software: I'm just using the .NET C# bindings to feed the input in programmatically.
Driver Version: 1.16.116
**Additional context**
This youtube video shows how I'm trying to use it.
https://www.youtube.com/watch?v=EngEEFEUyXw

**Comment by nefarius** [comment]
The value you set the axis to is way too small (less than 10% engaged), it's probably within the game/emulators dead zone so it's not registered. [Look at the documentation for the valid XINPUT_GAMEPAD ranges on the axes](https://docs.microsoft.com/en-us/windows/win32/api/xinput/ns-xinput-xinput_gamepad#members), relevant snippet:

> Left thumbstick x-axis value. Each of the thumbstick axis members is a signed value between -32768 and 32767 describing the position of the thumbstick. A value of 0 is centered. Negative values signify down or to the left. Positive values signify up or to the right.

Cheers

**Comment by jmoseman01** [comment]
You're right!

**Comment by jmoseman01** [comment]
I got it to work with the ps2 via socket :D!
https://www.youtube.com/watch?v=HrbeU0ZPyJo

server - hard coded network interface
https://github.com/jmoseman01/Ps2ViGEmClient

client - hard coded ip
https://github.com/jmoseman01/ps2ConnectToSocket
