### ISSUE TITLE
Trigger buttons are not working (DualShock4Button.TriggerLeft, DualShock4Button.TriggerRight)

### ISSUE THREAD

**Issue by stylerhun** [ViGEm/ViGEm.NET#14]
Hi!

I try to use the L2 and R2 buttons, but these 2 buttons are the only ones which are not working with remote play on PS4.

I try to use them in this way:

` controller.SetButtonState(DualShock4Button.TriggerLeft, true);
  Wait(500);
  controller.SetButtonState(DualShock4Button.TriggerLeft, false);`

unfortunately, nothing happens, Ps4 doesn't recognize the input. I've read in an other project's website, that L2 and R2 buttons are not buttons, reather than an axis, but I can find this buttons only under DualShock4Button.

What am I doing wrong?

Thank you!

**Comment by nefarius** [comment]
You probably also need to set the **slider** values. The triggers have a dual-function; they are reported both as a digital button and a slider (not axis) with a range from 0 to 255. There's a separate function and types available to set them to a value of your liking.

Cheers!

**Comment by TalaChartShiraz** [comment]
Dear nefarius,
I wanna use DualShock4Button to go to Left, Right, Up, and Down. What shall I do?
Sincerely,
Alireza

**Comment by nefarius** [comment]
@TalaChartShiraz you call `SetDPadDirection` with the appropriate value and delay you need.

**Comment by TalaChartShiraz** [comment]
```
 private void butRight_Click(object sender, EventArgs e)
        {

            controller.SetDPadDirection(DualShock4DPadDirection.East);
            Thread.Sleep(100);

        }
```
I  did, but how could I set the value to it?
It works, but I wanna go to the next item. By setting the value as 'East' it goes to the end item in the right side. I am going to go all items one by one.

**Comment by stylerhun** [comment]
> ```
>  private void butRight_Click(object sender, EventArgs e)
>         {
> 
>             controller.SetDPadDirection(DualShock4DPadDirection.East);
>             Thread.Sleep(100);
> 
>         }
> ```
> 
> I did, but how could I set the value to it?
> It works, but I wanna go to the next item. By setting the value as 'East' it goes to the end item in the right side. I am going to go all items one by one.

You can't. You can move the sticks to the right direction, there you can set values. In DPad, you cant. Here you can see how you can use the sticks:

```csharp
        /// <summary>
        /// Right stick to right
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void Button15_Click(object sender, EventArgs e)
        {
            controller.SetAxisValue(DualShock4Axis.RightThumbX, Convert.ToByte(255));
            Wait(100);
            controller.SetAxisValue(DualShock4Axis.RightThumbX, Convert.ToByte(128));
        }

        /// <summary>
        /// Right stick to Left 
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void Button16_Click(object sender, EventArgs e)
        {
            controller.SetAxisValue(DualShock4Axis.RightThumbX, Convert.ToByte(0));
            Wait(100);
            controller.SetAxisValue(DualShock4Axis.RightThumbX, Convert.ToByte(128));
        }

        /// <summary>
        /// Right stick to top
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void Button17_Click(object sender, EventArgs e)
        {
            controller.SetAxisValue(DualShock4Axis.RightThumbY, Convert.ToByte(0));
            Wait(100);
            controller.SetAxisValue(DualShock4Axis.RightThumbY, Convert.ToByte(128));
        }

        /// <summary>
        /// Right stick to bottom
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void Button18_Click(object sender, EventArgs e)
        {
            controller.SetAxisValue(DualShock4Axis.RightThumbY, Convert.ToByte(255));
            Wait(100);
            controller.SetAxisValue(DualShock4Axis.RightThumbY, Convert.ToByte(128));
        }

        /// <summary>
        /// Left stick to left
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void Button21_Click(object sender, EventArgs e)
        {
            controller.SetAxisValue(DualShock4Axis.LeftThumbX, Convert.ToByte(0));
            Wait(100);
            controller.SetAxisValue(DualShock4Axis.LeftThumbX, Convert.ToByte(128));
        }

        /// <summary>
        /// Left stick to right
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void Button22_Click(object sender, EventArgs e)
        {
            controller.SetAxisValue(DualShock4Axis.LeftThumbX, Convert.ToByte(255));
            Wait(100);
            controller.SetAxisValue(DualShock4Axis.LeftThumbX, Convert.ToByte(128));
        }

        /// <summary>
        /// Left stick to top
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void Button20_Click(object sender, EventArgs e)
        {
            controller.SetAxisValue(DualShock4Axis.LeftThumbY, Convert.ToByte(0));
            Wait(100);
            controller.SetAxisValue(DualShock4Axis.LeftThumbY, Convert.ToByte(128));
        }

        /// <summary>
        /// Left stick to bottom
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void Button19_Click(object sender, EventArgs e)
        {
            controller.SetAxisValue(DualShock4Axis.LeftThumbY, Convert.ToByte(255));
            Wait(100);
            controller.SetAxisValue(DualShock4Axis.LeftThumbY, Convert.ToByte(128));
        }
```

**Comment by stylerhun** [comment]
> You probably also need to set the **slider** values. The triggers have a dual-function; they are reported both as a digital button and a slider (not axis) with a range from 0 to 255. There's a separate function and types available to set them to a value of your liking.
> 
> Cheers!

Thank you! It works!
For anybody if needed later:

        /// <summary>
        /// L2
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void Button11_Click(object sender, EventArgs e)
        {
            controller.SetButtonState(DualShock4Button.TriggerLeft, true);
            controller.SetSliderValue(DualShock4Slider.LeftTrigger, 255);
            Wait(500);
            controller.SetSliderValue(DualShock4Slider.LeftTrigger, 0);
            controller.SetButtonState(DualShock4Button.TriggerLeft, false);
        }

**Comment by TalaChartShiraz** [comment]
Dear stylerhun,
Thanks a lot. It works.
