### ISSUE TITLE
How to use new Motion Sensing feature in .Net

### ISSUE THREAD

**Issue by pjsoftcoUser** [ViGEm/ViGEm.NET#15]
I tried to use the Discord channel to ask my question but it is not loading it(saying "Messages failed to load") so i got to come here to ask. I have updated to the latest library through nuget (1.17.178) but what method i should use to set the touchpad report or the gyro? basically the new features for DS4.

**Comment by nefarius** [comment]
Use the `SubmitRawReport`method, it allows you to submit the full report with all the missing features. You need to craft it yourself though, no supportive types are in the library yet.

**Comment by nefarius** [comment]
> I tried to use the Discord channel to ask my question but it is not loading it(saying "Messages failed to load") so i got to come here to ask.

You didn't complete anti bot verification.

**Comment by pjsoftcoUser** [comment]
> Use the `SubmitRawReport`method, it allows you to submit the full report with all the missing features. You need to craft it yourself though, no supportive types are in the library yet.

Are the supportive types on the way? And how it should look like if i craft it myself?!

**Comment by nefarius** [comment]
> > Use the `SubmitRawReport`method, it allows you to submit the full report with all the missing features. You need to craft it yourself though, no supportive types are in the library yet.
> 
> Are the supportive types on the way? And how it should look like if i craft it myself?!

Not from me, no. I got no time to work on the SDK. Look into the countless publications online on how a DS4 input report is crafted and you shall find guidance (DS4Windows sources for example).

Cheers

**Comment by pjsoftcoUser** [comment]
Thanks for responding, i will look into it!
