### ISSUE TITLE
ViGEm crashes silently with "prefer 32bit" ticked.

### ISSUE THREAD

**Issue by Daltz333** [ViGEm/ViGEm.NET#3]
ViGEm.net core/api/refine branch build will crash silently on 64 bit systems. It can be resolved by unticking the "prefer 32bit" in project properties.

1. Create a WPF project
2. Add the following code
```
ViGEmClient client = new ViGEmClient();
IVirtualGamepad pad = client.CreateXbox360Controller();

pad.Connect();
```
3. Run program
4. Observe crash

Windows 10 Pro 64bit
Latest build as of: https://github.com/ViGEm/ViGEm.NET/commit/1adc0528bfe33ac142cd3be4c97016a0bb0b434e

**Comment by nefarius** [comment]
I completely forgot how we intended to address or fix this 😲

**Comment by Daltz333** [comment]
Fixed in https://github.com/ViGEm/ViGEmClient/commit/d315abe8674e37bfe245ffd01273d8707f922847
