### ISSUE TITLE
Changing RightThumbX value does not work on newer refine API

### ISSUE THREAD

**Issue by Ryochan7** [ViGEm/ViGEm.NET#4]
**Describe the bug**

Trying to set RightThumbX of an Xbox 360 Controller when using a call like `SetAxisValue(Xbox360Axis.RightThumbX, value)` does not work. The call will change the value for RightThumbY instead. The problem boils down to a bad copy paste in the code.

https://github.com/ViGEm/ViGEm.NET/blob/core/api/refine/ViGEmClient/Targets/Xbox360/Xbox360Properties.cs#L213

```
public static Xbox360Axis RightThumbX = new RightThumbYAxis();
```

**To Reproduce**
Steps to reproduce the behavior (example):
1. Create IXbox360Controller instance
2. Call `SetAxisValue(Xbox360Axis.RightThumbX, value)` on instance
3. Output from HTML5 Gamepad Tester shows that RightThumbY is being changed rather than RightThumbX.

**Expected behavior**

RightThumbX value of the virtual Xbox 360 controller should be updated.

**System details (please complete the following information):**

 - OS: Windows 10 x64
 - Feeder software: DS4Windows
 - Driver Version: 1.14.3.0

**Comment by Daltz333** [comment]
Solved in https://github.com/ViGEm/ViGEm.NET/pull/5

**Comment by nefarius** [comment]
Copypasta is best pasta 😛 Merged.

**Comment by nefarius** [comment]
Fixed
