### ISSUE TITLE
Expose API to modify native report before sending

### ISSUE THREAD

**Issue by nefarius** [ViGEm/ViGEm.NET#6]
> Since the refine API has been brought up, I have a suggestion. Can the API be changed to allow the native report to be changed without the calls to SubmitNativeReport? I would like to change the controller state as much as needed and then have the final report sent when finished. As it is, having SubmitNativeReport called multiple times per gamepad poll is pretty slow.

@Ryochan7

**Comment by nefarius** [comment]
@Ryochan7 [is this methodology sufficient for your needs?](https://github.com/ViGEm/ViGEm.NET/commit/4f665003e31d4f84d5f7591760be04a2fa2c4de4)

**Comment by Ryochan7** [comment]
That should work.
